this.symbolObject = {
    "395": "wi-day-sleet-storm",
    "392": "wi-day-sleet-storm",
    "389": "wi-day-storm-showers",
    "386": "wi-day-storm-showers",
    "377": "wi-day-thunderstorm",
    "374": "wi-day-thunderstorm",
    "371": "wi-day-snow",
    "368": "wi-day-snow",
    "365": "wi-day-snow",
    "362": "wi-day-snow",
    "359": "wi-day-thunderstorm",
    "356": "wi-day-rain",
    "353": "wi-day-showers",
    "350": "wi-day-hail",
    "338": "wi-day-snow",
    "335": "wi-day-snow",
    "332": "wi-day-snow",
    "329": "wi-day-snow",
    "326": "wi-day-snow",
    "323": "wi-day-snow",
    "320": "wi-day-snow",
    "317": "wi-day-showers",
    "314": "wi-day-hail",
    "311": "wi-day-hail",
    "308": "wi-day-rain",
    "305": "wi-day-rain",
    "302": "wi-day-rain",
    "299": "wi-day-rain",
    "296": "wi-day-showers",
    "293": "wi-day-showers",
    "284": "wi-day-hail",
    "281": "wi-day-hail",
    "266": "wi-day-showers",
    "263": "wi-day-showers",
    "260": "wi-fog",
    "248": "wi-fog",
    "230": "wi-day-hail",
    "227": "wi-day-hail",
    "200": "wi-lightning",
    "185": "wi-day-hail",
    "182": "wi-day-hail",
    "179": "wi-day-snow",
    "176": "wi-day-rain",
    "143": "wi-fog",
    "122": "wi-cloudy",
    "119": "wi-cloudy",
    "116": "wi-day-sunny-overcast",
    "113": "wi-day-sunny"
};

this.statementObject = {
    "395": "Bring a umbrella",
    "392": "Bring a umbrella",
    "389": "Bring a umbrella",
    "386": "Bring a umbrella",
    "377": "Bring a umbrella",
    "374": "Bring a umbrella",
    "371": "Leeds is beautiful in the snow",
    "368": "Leeds is beautiful in the snow",
    "365": "Leeds is beautiful in the snow",
    "362": "Leeds is beautiful in the snow",
    "359": "Bring a umbrella",
    "356": "Bring a umbrella",
    "353": "Bring a umbrella",
    "350": "Stick to the Victoria Quarter",
    "338": "Leeds is beautiful in the snow",
    "335": "Leeds is beautiful in the snow",
    "332": "Leeds is beautiful in the snow",
    "329": "Leeds is beautiful in the snow",
    "326": "Leeds is beautiful in the snow",
    "323": "Leeds is beautiful in the snow",
    "320": "Leeds is beautiful in the snow",
    "317": "Bring a umbrella",
    "314": "Stick to the Victoria Quarter",
    "311": "Stick to the Victoria Quarter",
    "308": "Bring a umbrella",
    "305": "Bring a umbrella",
    "302": "Bring a umbrella",
    "299": "Bring a umbrella",
    "296": "Bring a umbrella",
    "293": "Bring a umbrella",
    "284": "Stick to the Victoria Quarter",
    "281": "Stick to the Victoria Quarter",
    "266": "Bring a umbrella",
    "263": "Bring a umbrella",
    "260": "Have a great day",
    "248": "Have a great day",
    "230": "Stick to the Victoria Quarter",
    "227": "Stick to the Victoria Quarter",
    "200": "wi-lightning",
    "185": "Stick to the Victoria Quarter",
    "182": "Stick to the Victoria Quarter",
    "179": "Leeds is beautiful in the snow",
    "176": "Bring a umbrella",
    "143": "Have a great day",
    "122": "All looks clear!",
    "119": "All looks clear!",
    "116": "Looking nice and warm",
    "113": "Forget the coat"
};